#!/usr/bin/env bash
#
# install-hooks.sh — generates .git/hooks/pre-commit
#
# Called by `npm run prepare` (runs on `npm install`).
# The generated hook runs:
#   1. Beads sync (flush pending changes) — skipped in Dolt server mode
#   2. Secret scan over the ADDED lines of the staged diff (repo is public)
#   3. ESLint + tsc --noEmit on staged .ts/.tsx/.js/.jsx files
#   4. cargo clippy on staged server/**/*.rs or server/Cargo.toml
#
# Skip all checks with: git commit --no-verify

set -euo pipefail

# ── Worktrees: nothing to install ─────────────────────────────────────
# A worktree's .git is a FILE ("gitdir: <path>"), not a directory. Its hooks
# live in the main repository's .git/hooks and are written by that checkout's
# own `npm install`, so there is genuinely nothing to do here.
#
# The check is deliberately git-free. `npm ci` inside a worktree invokes this
# script through whichever `bash` is first on PATH — on Windows that is WSL's,
# whose git reads the Windows-absolute path out of the .git file and resolves it
# relative to the WSL cwd:
#   fatal: not a git repository: /mnt/c/.../worktree/C:/.../.git/worktrees/...
# Under `set -e` that aborted `npm ci` with exit 128 (bweb-g80).
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/../.git" ]; then
  echo "install-hooks: worktree detected — hooks live in the main repository, nothing to do"
  exit 0
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"

# ── bd config: disable auto git-add (bd-beads-web-b9c) ────────────────
# bd v1.0.2 auto-export runs `git add issues.jsonl` relative to CWD,
# which creates stray files at worktree roots. Apply the config fix on
# every `npm install` so new clones and CI pick it up automatically.
# .beads/ is gitignored, so each checkout gets its own local config.yaml.
# bd itself walks up to find .beads/, so we let bd's own resolver gate us:
# if `bd config get` fails (no .beads/ found anywhere), skip silently.
if command -v bd >/dev/null 2>&1; then
  CURRENT_GIT_ADD="$(bd config get export.git-add 2>/dev/null || true)"
  if [ -n "$CURRENT_GIT_ADD" ] && [ "$CURRENT_GIT_ADD" != "false" ]; then
    if bd config set export.git-add false >/dev/null 2>&1; then
      echo "bd config: export.git-add=false (prevents stray issues.jsonl in worktrees)"
    fi
  fi
fi

# For worktrees, hooks live in the common git dir
HOOKS_DIR="$(git rev-parse --git-common-dir)/hooks"
mkdir -p "$HOOKS_DIR"

HOOK_PATH="$HOOKS_DIR/pre-commit"

cat > "$HOOK_PATH" << 'HOOK_EOF'
#!/bin/sh
#
# Pre-commit hook: beads sync + secret scan + lint + typecheck + clippy
# Auto-generated by scripts/install-hooks.sh — do not edit manually.
# Skip with: git commit --no-verify

# ── Secret scan ────────────────────────────────────────────────────────
# This repository is public: a secret that reaches a commit is effectively
# leaked (forks and clones never see a history rewrite). The scan looks at
# the ADDED lines of the staged diff only — never the working tree, never
# whole files — so it costs nothing on a normal commit.
#
# Reads a unified diff (git diff -U0) on stdin, prints findings on stdout,
# exits 1 when something was found. Escape hatches, in order of preference:
#   1. do not commit the secret;
#   2. `pragma: allowlist secret` on the offending line;
#   3. git commit --no-verify.
scan_secrets_diff() {
  awk '
# \42 = double quote, \47 = single quote (octal so this program can live
# inside a single-quoted shell string).

function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }

function mask(s,   n) {
  n = length(s)
  if (n <= 10) return substr(s, 1, 2) "***"
  return substr(s, 1, 4) "***" substr(s, n - 1) "  (" n " chars)"
}

function report(rule, snippet) {
  found++
  if (lineno > 0) printf "  %s:%d  [%s]\n", (file == "" ? "?" : file), lineno, rule
  else            printf "  %s  [%s]\n", (file == "" ? "?" : file), rule
  printf "      %s\n", snippet
}

# Same line, with the secret value itself masked out.
function masked_line(m, v,   p) {
  p = index(m, v)
  if (p == 0) return trim(m)
  return trim(substr(m, 1, p - 1) mask(v) substr(m, p + length(v)))
}

# Does a candidate value look like a real secret rather than a placeholder,
# a code reference or an English sentence? Everything here exists to keep
# false positives near zero — a hook that cries wolf gets --no-verify-ed.
function secretish(v,   lv) {
  if (length(v) < 8) return 0
  if (v ~ /[ \t]/) return 0                                  # sentences
  lv = tolower(v)
  if (v ~ /^[-+]?[0-9][0-9.]*$/) return 0                    # numbers, versions
  if (v ~ /^[<{$%(\[]/) return 0                             # ${X}, <your-key>, %s
  if (v ~ /\$\{|\$\(|\{\{|<[A-Za-z_\/]/) return 0            # interpolation, tags
  if (v ~ /^[A-Za-z]:[\\\/]/ || v ~ /^[.~\/\\]/) return 0    # file paths
  if (v ~ /^[A-Za-z][A-Za-z0-9+.-]*:\/\//) return 0          # URLs
  if (lv ~ /^(changeme|change_me|password|passwd|secret|token|apikey|api_key|accesskey|access_key|credentials|placeholder|redacted|removed|hidden|masked|dummy|example|sample|test|testing|fake|none|null|nil|true|false|undefined|unset|todo|required|optional)$/) return 0
  if (lv ~ /(^|[^a-z])(your|my|some|the|a)[_-]?(password|passwd|secret|token|key|value)/) return 0
  if (lv ~ /(_here$|-here$|placeholder|redacted|changeme|example|sample|dummy|xxxx|\*\*\*|\.\.\.)/) return 0
  if (lv ~ /^[x*.\-_]+$/) return 0                           # xxxxxxxx, ********
  # Code references: var.github_token, process.env.API_KEY, config.secret_key
  if (v !~ /[0-9]/ && v ~ /^[A-Za-z_][A-Za-z0-9_.]*[_.][A-Za-z0-9_.]*$/) return 0
  # Real secrets mix letters and digits; long opaque strings pass anyway.
  if (length(v) < 24 && (v !~ /[0-9]/ || v !~ /[A-Za-z]/)) return 0
  return 1
}

function value_of(m,   v) {                                  # key = \42val\42 -> val
  v = m
  sub(/^[^:=]*[:=]+[ \t]*/, "", v)
  sub(/^[\42\47]/, "", v)
  sub(/[\42\47][^\42\47]*$/, "", v)
  return v
}

function check(c,   lc, m, v) {
  if (c ~ /pragma:[ \t]*allowlist[ \t]+secret/) return       # explicit opt-out
  lc = tolower(c)

  if (match(c, /-----BEGIN [A-Z0-9 ]{0,24}PRIVATE KEY-----/)) {
    report("private-key", substr(c, RSTART, RLENGTH)); return
  }
  if (match(c, /gh[pousr]_[A-Za-z0-9]{20,}/) ||
      match(c, /github_pat_[A-Za-z0-9_]{22,}/)) {
    report("github-token", mask(substr(c, RSTART, RLENGTH))); return
  }
  if (match(c, /xox[baprs]-[A-Za-z0-9-]{10,}/)) {
    report("slack-token", mask(substr(c, RSTART, RLENGTH))); return
  }
  if (match(c, /(^|[^A-Za-z0-9])AKIA[0-9A-Z]{16}/)) {
    report("aws-access-key", mask(trim(substr(c, RSTART, RLENGTH)))); return
  }
  if (match(c, /sk-ant-[A-Za-z0-9_-]{20,}/)) {
    report("anthropic-key", mask(substr(c, RSTART, RLENGTH))); return
  }

  # key = "value" / key: "value" — a quoted literal only, so that
  # `token = process.env.X` and `let (password, _) = resolve(..)` stay quiet.
  if (match(lc, /[a-z0-9_.-]*(password|passwd|secret|token|api[_-]?key|apikey|access[_-]?key)[\42\47]?[ \t]*[:=]+[ \t]*[\42\47][^\42\47]{8,}[\42\47]/)) {
    m = substr(c, RSTART, RLENGTH)
    v = value_of(m)
    if (secretish(v)) { report("hardcoded-secret", masked_line(m, v)); return }
  }
  # KEY=value at the start of a line (.env files, shell exports)
  if (match(lc, /^[ \t]*(export[ \t]+)?[a-z0-9_.-]*(password|passwd|secret|token|api[_-]?key|apikey|access[_-]?key)[ \t]*=[ \t]*[^ \t\42\47#]{8,}/)) {
    m = substr(c, RSTART, RLENGTH)
    v = value_of(m)
    if (secretish(v)) { report("env-secret", masked_line(m, v)); return }
  }

  # Private network addresses of the home lab (10.x.x.x, 192.168.x.x)
  if (match(c, /(^|[^0-9.])(10|192\.168)\.[0-9]{1,3}\.[0-9]{1,3}(\.[0-9]{1,3})?([^0-9.]|$)/)) {
    m = trim(substr(c, RSTART, RLENGTH))
    if (m ~ /(^|[^0-9.])10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}([^0-9.]|$)/ ||
        m ~ /(^|[^0-9.])192\.168\.[0-9]{1,3}\.[0-9]{1,3}([^0-9.]|$)/) {
      report("private-ip", m); return
    }
  }
}

# ── diff walker: track current file and the line number of each + line ──
/^diff --git /   { isnew = 0; file = ""; skip = 0; next }
/^new file mode/ { isnew = 1; next }
/^rename to /    { isnew = 1; next }

/^\+\+\+ / {
  file = substr($0, 5)
  sub(/^b\//, "", file)
  skip = 0
  if (file == "/dev/null") { skip = 1; next }
  # Generated and example files: never a real secret, always noisy.
  if (file ~ /(\.example|\.sample|\.template|\.dist|\.lock|\.snap|-lock\.json|\.min\.js|\.map)$/) skip = 1
  if (file ~ /(^|\/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock)$/) skip = 1
  if (!skip && isnew && file ~ /(\.pem|\.key|\.pfx|\.p12|\.jks|\.keystore|\.ppk|\.asc)$/) {
    lineno = 0; report("secret-file", "new file: " file)
  }
  if (!skip && isnew && file ~ /(^|\/)(\.env|\.env\..*|\.dolt\.env|id_rsa|id_dsa|id_ecdsa|id_ed25519|credentials)$/) {
    lineno = 0; report("secret-file", "new file: " file)
  }
  next
}

/^@@ / {
  plus = $3
  sub(/^\+/, "", plus)
  split(plus, a, ",")
  lineno = a[1] + 0
  next
}

/^\+/ {
  if (skip) next
  check(substr($0, 2))
  lineno++
  next
}

END { if (found) exit 1 }
'
}

# Test / CI entry point — same code path as the commit-time scan:
#   git diff -U0 --diff-filter=ACMR HEAD~1 HEAD | .git/hooks/pre-commit --scan-diff
if [ "${1:-}" = "--scan-diff" ]; then
  scan_secrets_diff
  exit $?
fi

# ── Beads sync ─────────────────────────────────────────────────────────
# Flush pending bd changes to .beads/issues.jsonl before commit.
# Skipped in Dolt server mode: the central Dolt server is the source of
# truth there, so a local issues.jsonl only triggers redundant auto-imports
# on every subsequent bd call (and git add is a no-op — it's gitignored).

if command -v bd >/dev/null 2>&1; then
  BEADS_DIR=""
  if git rev-parse --git-dir >/dev/null 2>&1; then
    if [ "$(git rev-parse --git-dir)" != "$(git rev-parse --git-common-dir)" ]; then
      MAIN_REPO_ROOT="$(dirname "$(git rev-parse --git-common-dir)")"
      if [ -d "$MAIN_REPO_ROOT/.beads" ]; then
        BEADS_DIR="$MAIN_REPO_ROOT/.beads"
      fi
    else
      if [ -d .beads ]; then
        BEADS_DIR=".beads"
      fi
    fi
  fi

  # Detect Dolt server mode from metadata.json — skip the JSONL flush if so.
  BEADS_SERVER_MODE=0
  if [ -n "$BEADS_DIR" ] && [ -f "$BEADS_DIR/metadata.json" ]; then
    if grep -q '"dolt_mode"[[:space:]]*:[[:space:]]*"server"' "$BEADS_DIR/metadata.json" 2>/dev/null; then
      BEADS_SERVER_MODE=1
    fi
  fi

  if [ -n "$BEADS_DIR" ] && [ "$BEADS_SERVER_MODE" -eq 0 ]; then
    if ! bd export -o "$BEADS_DIR/issues.jsonl" >/dev/null 2>&1; then
      echo "Error: Failed to flush bd changes to JSONL" >&2
      echo "Run 'bd export -o .beads/issues.jsonl' manually to diagnose" >&2
      exit 1
    fi
    if [ -f "$BEADS_DIR/issues.jsonl" ]; then
      if [ "$(git rev-parse --git-dir)" = "$(git rev-parse --git-common-dir)" ]; then
        git add "$BEADS_DIR/issues.jsonl" 2>/dev/null || true
      fi
    fi
  fi
fi

# ── Resolve repo root ─────────────────────────────────────────────────

REPO_ROOT="$(git rev-parse --show-toplevel)"

# In a worktree, node_modules lives in the main checkout (git-common-dir parent).
# In the main repo, it's the same as REPO_ROOT.
if [ "$(git rev-parse --git-dir)" != "$(git rev-parse --git-common-dir)" ]; then
  NODE_MODULES_ROOT="$(dirname "$(git rev-parse --git-common-dir)")"
else
  NODE_MODULES_ROOT="$REPO_ROOT"
fi

# ── Collect staged files ───────────────────────────────────────────────

STAGED_FILES="$(git diff --cached --name-only --diff-filter=ACMR)"
if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

# ── Secret scan (runs first: a leak must never ride along with lint noise) ──

if ! command -v awk >/dev/null 2>&1; then
  echo "Warning: awk not found, SKIPPING the secret scan — check the diff yourself" >&2
else
  SECRET_FINDINGS="$(git diff --cached -U0 --diff-filter=ACMR | scan_secrets_diff)"
  SECRET_STATUS=$?
  if [ "$SECRET_STATUS" -ne 0 ]; then
    echo "" >&2
    echo "COMMIT BLOCKED — possible secrets in the staged changes:" >&2
    echo "" >&2
    printf '%s\n' "$SECRET_FINDINGS" >&2
    echo "" >&2
    echo "This repository is public. If any of these is a real secret:" >&2
    echo "  1. unstage/remove it (env var or %APPDATA%\\beads\\credentials instead)," >&2
    echo "  2. rotate it — assume anything committed here is already public." >&2
    echo "If it is a false positive:" >&2
    echo "  - add 'pragma: allowlist secret' to that line, or" >&2
    echo "  - bypass this check deliberately: git commit --no-verify" >&2
    echo "" >&2
    exit 1
  fi
fi

FRONTEND_FILES=""
RUST_FILES=""
HAS_CARGO_TOML=0

for f in $STAGED_FILES; do
  case "$f" in
    *.ts|*.tsx|*.js|*.jsx)
      FRONTEND_FILES="$FRONTEND_FILES $f"
      ;;
    server/*.rs)
      RUST_FILES="$RUST_FILES $f"
      ;;
    server/Cargo.toml)
      HAS_CARGO_TOML=1
      ;;
  esac
done

EXIT_CODE=0

# ── Frontend checks ───────────────────────────────────────────────────

if [ -n "$FRONTEND_FILES" ]; then
  if [ ! -d "$NODE_MODULES_ROOT/node_modules" ]; then
    echo "Warning: node_modules not found, skipping frontend checks" >&2
    echo "  Run 'npm install' to enable pre-commit linting" >&2
  else
    echo "Running ESLint on staged files..."
    # shellcheck disable=SC2086
    if ! "$NODE_MODULES_ROOT/node_modules/.bin/eslint" --max-warnings 0 $FRONTEND_FILES; then
      echo "ESLint failed. Fix errors or run: npx eslint --fix <files>" >&2
      EXIT_CODE=1
    fi

    echo "Running TypeScript type-check..."
    if ! "$NODE_MODULES_ROOT/node_modules/.bin/tsc" --noEmit; then
      echo "TypeScript type-check failed." >&2
      EXIT_CODE=1
    fi
  fi
fi

# ── Rust checks ────────────────────────────────────────────────────────

if [ -n "$RUST_FILES" ] || [ "$HAS_CARGO_TOML" -eq 1 ]; then
  if ! command -v cargo >/dev/null 2>&1; then
    echo "Warning: cargo not found, skipping Rust checks" >&2
  else
    # Share one cargo target across worktrees: a fresh worktree would otherwise
    # rebuild everything from scratch (~20 min) just to run clippy. git-common-dir
    # points at the main repo's .git and equals git-dir in a normal checkout.
    if [ -z "${CARGO_TARGET_DIR:-}" ]; then
      COMMON_DIR="$(git rev-parse --git-common-dir 2>/dev/null)"
      if [ -n "$COMMON_DIR" ]; then
        case "$COMMON_DIR" in
          /*|[A-Za-z]:*) ;;
          *) COMMON_DIR="$(git rev-parse --show-toplevel)/$COMMON_DIR" ;;
        esac
        MAIN_REPO_ROOT="$(dirname "$COMMON_DIR")"
        if [ -d "$MAIN_REPO_ROOT/server" ]; then
          CARGO_TARGET_DIR="$MAIN_REPO_ROOT/server/target"
          export CARGO_TARGET_DIR
        fi
      fi
    fi

    # clippy can be missing on the default toolchain while another installed
    # toolchain has it — on Windows the default is often msvc, which this
    # project cannot even build (no MSVC linker; we build the gnu target).
    # Empty CLIPPY_TOOLCHAIN means "default toolchain is fine".
    CLIPPY_TOOLCHAIN=""
    CLIPPY_FOUND=0
    if cargo clippy --version >/dev/null 2>&1; then
      CLIPPY_FOUND=1
    elif command -v rustup >/dev/null 2>&1; then
      for tc in $(rustup toolchain list | cut -d' ' -f1); do
        if cargo "+$tc" clippy --version >/dev/null 2>&1; then
          CLIPPY_TOOLCHAIN="+$tc"
          CLIPPY_FOUND=1
          break
        fi
      done
    fi

    if [ "$CLIPPY_FOUND" -eq 0 ]; then
      echo "Warning: cargo clippy not available on any installed toolchain, skipping Rust checks" >&2
      echo "  Install it with: rustup component add clippy" >&2
    else
      echo "Running cargo clippy on server${CLIPPY_TOOLCHAIN:+ ($CLIPPY_TOOLCHAIN)}..."
      if ! cargo ${CLIPPY_TOOLCHAIN} clippy --manifest-path "$REPO_ROOT/server/Cargo.toml" -- -D warnings; then
        echo "Cargo clippy failed." >&2
        EXIT_CODE=1
      fi
    fi
  fi
fi

exit $EXIT_CODE
HOOK_EOF

chmod +x "$HOOK_PATH"
echo "Pre-commit hook installed at $HOOK_PATH"
